function Z = updateZ(X,P,A,E,Z,S,Q,ExistIndex,W_bar,Y_1,Y_2,alpha,mu,omega1,omega2,omega3,v)
for i = 1:v
    Z{i} =updateT( ...
        (2*alpha*getB((A{i}'*P{i}*X{i}),ExistIndex,i) ...
        +(mu*W_bar{i}-Y_1{i}) ...
        +(mu*(omega1*S+omega2*Q{i}+omega3*E{i})-Y_2{i}) ...
        ) ...
        ./(2*alpha+2*mu));

end
end